// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
try { require("dotenv/config"); } catch(e) {}

export default {
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
};
